### ISSUE TITLE
CUDA out of memory 怎么办？

### ISSUE THREAD

**Issue by GeLink9999** [cfzd/Ultra-Fast-Lane-Detection#175]
Using demo，when executing "python train.py configs/path_to_your_config"，my computer cannot run the code normally with an error "CUDA out of memory"，mine is 2G. I used watch command to see the real-time CUDA memory. In the beginning only less than 100M memory was used. When running the code, soon it reaches full memory.

**Comment by cfzd** [comment]
@GeLink9999 
调小config中的batch_size就好了

**Comment by GeLink9999** [comment]
> @GeLink9999
> 调小config中的batch_size就好了

Thanks. I have tried --batchsize 1 or 8 or 32. It didn't work.

**Comment by cfzd** [comment]
@GeLink9999 
在我这边batch size为32时cuda mem占用大约为7G，所以batch size小于8应该是可以的，你或许试试2,3,4吧

**Comment by GeLink9999** [comment]
> @GeLink9999
> 在我这边batch size为32时cuda mem占用大约为7G，所以batch size小于8应该是可以的，你或许试试2,3,4吧
Thanks. I just tried and it didn't work. Please see the pic, Thanks for your help.


![1](https://user-images.githubusercontent.com/56419000/109157850-8a673800-77ad-11eb-92dd-8fbe4bcad3f2.png)

**Comment by cfzd** [comment]
@GeLink9999 
如果还不行的话，尝试换个设备吧。2G显存的显卡估计不太行，就算跑起来了，训练速度估计也不是很乐观。

**Comment by GeLink9999** [comment]
谢谢
